### ISSUE TITLE
[TASK] Add information to the course info dropdown menus

### ISSUE THREAD

**Issue by condyl** [iOlivers/BrockVisualTimeTable#12]
When we add a course, we need to show some course information, like the instructor, section/lab/tutorial/... number, and probably more (maybe prerequisites in the future?).  

![image](https://github.com/user-attachments/assets/ae8a7242-16de-4853-a520-8cf2c266ec2f)

This involves more work than it seems, as each course can have different lecture sections in the same term taught by different instructors.  This means that this would need to update whenever the user chooses a new timetable.  This may require a total revamp of how the list of courses is passed from InputFormComponent.jsx to CourseListComponent.jsx.

It will likely be easier to just remove the dropdown temporarily and worry about it later.

**Comment by iOlivers** [comment]
Implemented as of commit: https://github.com/iOlivers/BrockVisualTimeTable/commit/aa67b10dc52c11bd7110e7ca8f2e63e98f94f4ad
