### ISSUE TITLE
[BUG FIX] Clicking "ADD COURSE" multiple times before the first click registers adds multiple duplicate timetables

### ISSUE THREAD

**Issue by condyl** [iOlivers/BrockVisualTimeTable#9]
This issue should only effect people with incredible slow internet.  If you click the "ADD COURSE" button multiple times before the course actually "gets added", it will duplicate the course.  For example, it could take 2-3 seconds for the course to be added, and during that time, if I click again, it will add again.

The solution for this would to add a hidden cooldown that prevents the user from doing this (or maybe just disabling the button until the course is confirmed added), and likely add some sort of [progress/loading indicator](https://mui.com/material-ui/react-progress/#interactive-integration).

**Comment by iOlivers** [comment]
Have not been able to reproduce is so far, furthering the likelihood that this is an unstable/slow internet related issue.
